image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
stages:
  - plan
  - apply

plan:
  stage: plan
  before_script:
  - rm -rf .terraform
  - terraform --version
  - export AWS_ACCESS_KEY_ID=$ACCESS_KEY
  - export AWS_SECRET_ACCESS_KEY=$SECRET_KEY
  - terraform init
  script:
    - terraform plan -out "planfile"
  artifacts:
    paths:
      - planfile
apply:
  stage: apply
  before_script:
  - rm -rf .terraform
  - terraform --version
  - export AWS_ACCESS_KEY_ID=$ACCESS_KEY
  - export AWS_SECRET_ACCESS_KEY=$SECRET_KEY
  - terraform init
  script:
    - terraform apply -input=false "planfile"
  dependencies:
    - plan
  when: manual
