image: docker:latest
services:
  - docker:dind
variables:
  DOCKER_DRIVER: overlay
stages:
  - build-maven
maven_build:
  image: maven:latest
  stage: build-maven
  script:
    - git checkout -f master
    - git config --local user.email "karlazzam93@gmail.com"
    - git config --local user.name "karlazzam"
    - echo "Building project with maven"
    - mvn -e -DGIT_USER=${GIT_USER} -DGIT_PW=${GIT_PW} -DscmCommentPrefix="[ci skip]" -B release:clean release:prepare
  artifacts:
    paths:
      - target/*.jar
  retry: 2
  only:
    changes:
      - pom.xml
      - .gitlab-ci.yml 
