image: docker:latest
services:
  - docker:dind
variables:
  DOCKER_DRIVER: overlay
  APP_NAME: REPLACE_ME
stages:
  - build-docker
docker_build:
  image: docker:latest
  stage: build-docker
  script:
  - echo "Logging in to docker"
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin registry.gitlab.com
  - cp -R target docker/target
  - cd target
  - SERVICE_NAME=$(find . -type f -name '*.jar' | cut -c 3- | rev | cut -c 14- | sed 's/-/:/' | rev);
  - echo ${SERVICE_NAME}
  - cd ..
  - echo "Building docker image"
  - docker build -t registry.gitlab.com/karlazzam/$APP_NAME ./docker
  - echo "Pushing docker image"
  - docker push registry.gitlab.com/karlazzam/$APP_NAME
  only:
    changes:
      - pom.xml
      - docker/Dockerfile
      - .gitlab-ci.yml 


