image: docker:latest
services:
  - docker:dind
variables:
  DOCKER_DRIVER: overlay
stages:
  - build-docker
docker_build:
  image: docker:latest
  stage: build-docker
  script:
  - echo "Logging in to docker"
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin registry.gitlab.com
  - cp -R target docker/target
  - cd target
  - SERVICE_NAME=$(find . -type f -name '*.jar' | cut -c 3- | rev | cut -c 14- | sed 's/-/:/' | rev);
  - echo "Service name:" ${SERVICE_NAME}
  - cd ..
  - echo "Building docker image"
  - docker build -t registry.gitlab.com/karlazzam/$SERVICE_NAME ./docker
  - echo "Pushing docker image"
  - docker push registry.gitlab.com/karlazzam/$SERVICE_NAME
  except:
    changes:
      - .gitlab-ci.yml 
      - docker/**/*


