image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
stages:
  - plan_vpc
  - apply_vpc

plan_vpc:
  stage: plan_vpc
  before_script:
  - rm -rf .terraform
  - terraform --version
  - export AWS_ACCESS_KEY_ID=$ACCESS_KEY
  - export AWS_SECRET_ACCESS_KEY=$SECRET_KEY
  - terraform init
  script:
    - terraform plan -target module.vpc -out "planfile-vpc"
  artifacts:
    paths:
      - planfile-vpc

apply_vpc:
  stage: apply_vpc
  before_script:
  - rm -rf .terraform
  - terraform --version
  - export AWS_ACCESS_KEY_ID=$ACCESS_KEY
  - export AWS_SECRET_ACCESS_KEY=$SECRET_KEY
  - terraform init
  script:
    - terraform apply -target module.vpc -input=false "planfile-vpc"
  dependencies:
    - plan_vpc
  when: manual
