image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
stages:
  - setup-deploy-tf
  - plan-vpc
  - apply-vpc

setup_deploy_tf_prod:
  stage: setup-deploy-tf
  script:
    - mv prod/deploy.tf deploy.tf
  only:
    refs:
      - master

setup_deploy_tf_dev:
  stage: setup-deploy-tf
  script:
    - mv dev/deploy.tf deploy.tf
  only:
    refs:
      - develop

plan_vpc_dev:
  stage: plan-vpc
  before_script:
  - rm -rf .terraform
  - terraform --version
  - export AWS_ACCESS_KEY_ID=$ACCESS_KEY
  - export AWS_SECRET_ACCESS_KEY=$SECRET_KEY
  - terraform init
  script:
    - terraform plan -target module.vpc -out "planfile-vpc"
  environment:
    name: dev
  artifacts:
    paths:
      - planfile-vpc

plan_vpc_prod:
  stage: plan-vpc
  before_script:
  - rm -rf .terraform
  - terraform --version
  - export AWS_ACCESS_KEY_ID=$ACCESS_KEY
  - export AWS_SECRET_ACCESS_KEY=$SECRET_KEY
  - terraform init
  script:
    - terraform plan -target module.vpc -out "planfile-vpc"
  environment:
    name: prod
  artifacts:
    paths:
      - planfile-vpc

apply_vpc_dev:
  stage: apply-vpc
  before_script:
  - rm -rf .terraform
  - terraform --version
  - export AWS_ACCESS_KEY_ID=$ACCESS_KEY
  - export AWS_SECRET_ACCESS_KEY=$SECRET_KEY
  - terraform init
  script:
    - terraform apply -target module.vpc -input=false "planfile-vpc"
  environment:
    name: dev
  dependencies:
    - plan_vpc_dev
  when: manual

apply_vpc_prod:
  stage: apply-vpc
  before_script:
  - rm -rf .terraform
  - terraform --version
  - export AWS_ACCESS_KEY_ID=$ACCESS_KEY
  - export AWS_SECRET_ACCESS_KEY=$SECRET_KEY
  - terraform init
  script:
    - terraform apply -target module.vpc -input=false "planfile-vpc"
  environment:
    name: prod
  dependencies:
    - plan_vpc_prod
  when: manual
