---
.terraform_dev_template: &terraform_dev_template
  before_script:
    - rm -rf .terraform
    - mv terraform/dev/vpc/deploy.tf deploy.tf
    - mv terraform/dev/vpc/output.tf output.tf
    - terraform --version
    - export AWS_ACCESS_KEY_ID=$ACCESS_KEY
    - export AWS_SECRET_ACCESS_KEY=$SECRET_KEY
    - terraform init
  environment:
    name: dev
  only:
    refs:
      - develop

.terraform_prod_template: &terraform_prod_template
  before_script:
    - rm -rf .terraform
    - mv terraform/prod/vpc/deploy.tf deploy.tf
    - mv terraform/prod/vpc/output.tf output.tf
    - terraform --version
    - export AWS_ACCESS_KEY_ID=$ACCESS_KEY
    - export AWS_SECRET_ACCESS_KEY=$SECRET_KEY
    - terraform init
  environment:
    name: prod
  only:
    refs:
      - master

image:
  name: hashicorp/terraform:0.12.29
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
stages:
  - destroy-vpc
  - plan-vpc
  - apply-vpc

plan_vpc_dev:
  stage: plan-vpc
  <<: *terraform_dev_template
  script:
    - terraform plan -target module.vpc -out "planfile-vpc"
  artifacts:
    paths:
      - planfile-vpc
  when: always

plan_vpc_prod:
  stage: plan-vpc
  <<: *terraform_prod_template
  script:
    - terraform plan -target module.vpc -out "planfile-vpc"
  artifacts:
    paths:
      - planfile-vpc
  when: always

apply_vpc_dev:
  stage: apply-vpc
  <<: *terraform_dev_template
  script:
    - terraform apply -target module.vpc -input=false "planfile-vpc"
  dependencies:
    - plan_vpc_dev
  when: on_success

apply_vpc_prod:
  stage: apply-vpc
  <<: *terraform_prod_template
  script:
    - terraform apply -target module.vpc -input=false "planfile-vpc"
  dependencies:
    - plan_vpc_prod
  when: on_success

destroy_vpc_dev:
  stage: destroy-vpc
  <<: *terraform_dev_template
  script:
    - terraform destroy -target module.vpc -force
  when: manual

destroy_vpc_prod:
  stage: destroy-vpc
  <<: *terraform_prod_template
  script:
    - terraform destroy -target module.vpc -force
  when: manual
