---
image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
stages:
  - plan-vpc
  - apply-vpc

plan_vpc_dev:
  stage: plan-vpc
  before_script:
    - rm -rf .terraform
    - terraform --version
    - export AWS_ACCESS_KEY_ID=$ACCESS_KEY
    - export AWS_SECRET_ACCESS_KEY=$SECRET_KEY
    - terraform init
  script:
    - mv dev/deploy.tf deploy.tf
    - terraform plan -target module.vpc -out "planfile-vpc"
  artifacts:
    paths:
      - planfile-vpc
  environment:
    name: dev
  only:
    refs:
      - develop

plan_vpc_prod:
  stage: plan-vpc
  before_script:
    - rm -rf .terraform
    - mv prod/deploy.tf deploy.tf
    - terraform --version
    - export AWS_ACCESS_KEY_ID=$ACCESS_KEY
    - export AWS_SECRET_ACCESS_KEY=$SECRET_KEY
    - terraform init
  script:
    - terraform plan -target module.vpc -out "planfile-vpc"
  artifacts:
    paths:
      - planfile-vpc
  environment:
    name: prod
  only:
    refs:
      - master

apply_vpc_dev:
  stage: apply-vpc
  before_script:
    - rm -rf .terraform
    - mv dev/deploy.tf deploy.tf
    - terraform --version
    - export AWS_ACCESS_KEY_ID=$ACCESS_KEY
    - export AWS_SECRET_ACCESS_KEY=$SECRET_KEY
    - terraform init
  script:
    - terraform apply -target module.vpc -input=false "planfile-vpc"
  dependencies:
    - plan_vpc_dev
  environment:
    name: dev
  only:
    refs:
      - develop
  when: manual

apply_vpc_prod:
  stage: apply-vpc
  before_script:
    - rm -rf .terraform
    - mv prod/deploy.tf deploy.tf
    - terraform --version
    - export AWS_ACCESS_KEY_ID=$ACCESS_KEY
    - export AWS_SECRET_ACCESS_KEY=$SECRET_KEY
    - terraform init
  script:
    - terraform apply -target module.vpc -input=false "planfile-vpc"
  dependencies:
    - plan_vpc_prod
  environment:
    name: prod
  only:
    refs:
      - master
  when: manual
